name: Run PHPUnit Tests

on:
  push:
    branches: [main]  # Run tests on pushes to the main branch (or adjust to your preferred branch)
  pull_request:
    branches: [main]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.2]  # Specify PHP versions you want to test against

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox
